Repository kryoniteorg/kryo-proxy-sync, pull requests merged in 2022-01, with the labels that each got.

#5 feat: Initial project setup
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/label-sync.yaml
  .github/workflows/main.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/wrapper-validation.yaml
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lombok.config
  settings.gradle.kts
  src/main/java/org/kryonite/kryoproxysync/KryoProxySyncPlugin.java
  src/test/java/org/kryonite/kryoproxysync/KryoProxySyncPluginTest.java
Labels: feature

#6 fix: Rename to KryoniteOrg to fit domain
  .github/workflows/label-sync.yaml
  .github/workflows/main.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/wrapper-validation.yaml
  build.gradle.kts
Labels: bugfix

#7 feat: Sync player count between Velocity servers
  build.gradle.kts
  src/main/java/org/kryonite/kryoproxysync/KryoProxySyncPlugin.java
  src/main/java/org/kryonite/kryoproxysync/listener/ProxyPingListener.java
  src/main/java/org/kryonite/kryoproxysync/messaging/MessagingController.java
  src/main/java/org/kryonite/kryoproxysync/messaging/consumer/PlayerCountChangedConsumer.java
  src/main/java/org/kryonite/kryoproxysync/messaging/message/PlayerCountChanged.java
  src/main/java/org/kryonite/kryoproxysync/playercount/PlayerCountManager.java
  src/test/java/org/kryonite/kryoproxysync/KryoProxySyncPluginTest.java
  src/test/java/org/kryonite/kryoproxysync/listener/ProxyPingListenerTest.java
  src/test/java/org/kryonite/kryoproxysync/messaging/MessagingControllerTest.java
  src/test/java/org/kryonite/kryoproxysync/messaging/consumer/PlayerCountChangedConsumerTest.java
  src/test/java/org/kryonite/kryoproxysync/playercount/PlayerCountManagerTest.java
Labels: feature, minor

#8 feat: Add server ping description and sample players
  build.gradle.kts
  src/main/java/org/kryonite/kryoproxysync/KryoProxySyncPlugin.java
  src/main/java/org/kryonite/kryoproxysync/listener/ProxyPingListener.java
  src/main/java/org/kryonite/kryoproxysync/persistence/entity/ServerPingEntity.java
  src/main/java/org/kryonite/kryoproxysync/persistence/repository/ServerPingRepository.java
  src/main/java/org/kryonite/kryoproxysync/persistence/repository/impl/MariaDbServerPingRepository.java
  src/main/java/org/kryonite/kryoproxysync/serverping/ServerPingManager.java
  src/test/java/org/kryonite/kryoproxysync/KryoProxySyncPluginTest.java
  src/test/java/org/kryonite/kryoproxysync/listener/ProxyPingListenerTest.java
  src/test/java/org/kryonite/kryoproxysync/persistence/repository/impl/MariaDbServerPingRepositoryTest.java
  src/test/java/org/kryonite/kryoproxysync/serverping/ServerPingManagerTest.java
Labels: feature, minor

#14 feat: Add maintenance command
  build.gradle.kts
  src/main/java/org/kryonite/kryoproxysync/KryoProxySyncPlugin.java
  src/main/java/org/kryonite/kryoproxysync/command/MaintenanceCommand.java
  src/main/java/org/kryonite/kryoproxysync/listener/PlayerJoinListener.java
  src/main/java/org/kryonite/kryoproxysync/maintenance/MaintenanceManager.java
  src/main/java/org/kryonite/kryoproxysync/messaging/MessagingController.java
  src/main/java/org/kryonite/kryoproxysync/messaging/consumer/MaintenanceChangedConsumer.java
  src/main/java/org/kryonite/kryoproxysync/messaging/message/MaintenanceChanged.java
  src/main/java/org/kryonite/kryoproxysync/persistence/repository/MaintenanceRepository.java
  src/main/java/org/kryonite/kryoproxysync/persistence/repository/impl/MariaDbMaintenanceModeRepository.java
  src/test/java/org/kryonite/kryoproxysync/command/MaintenanceCommandTest.java
  src/test/java/org/kryonite/kryoproxysync/listener/PlayerJoinListenerTest.java
  src/test/java/org/kryonite/kryoproxysync/maintenance/MaintenanceManagerTest.java
  src/test/java/org/kryonite/kryoproxysync/messaging/MessagingControllerTest.java
  src/test/java/org/kryonite/kryoproxysync/messaging/consumer/MaintenanceChangedConsumerTest.java
  src/test/java/org/kryonite/kryoproxysync/persistence/repository/impl/MariaDbMaintenanceModeRepositoryTest.java
Labels: feature

#16 feat: Increase test coverage
  src/main/java/org/kryonite/kryoproxysync/playercount/PlayerCountManager.java
  src/test/java/org/kryonite/kryoproxysync/messaging/MessagingControllerTest.java
  src/test/java/org/kryonite/kryoproxysync/persistence/repository/impl/MariaDbConfigRepositoryTest.java
  src/test/java/org/kryonite/kryoproxysync/playercount/PlayerCountManagerTest.java
Labels: feature
